[package]
name = "comprehensive_rust"
version = "0.1.0"
authors = ["Vighnesh Iyer <vighnesh.iyer@berkeley.edu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
